### PR TITLE
minor changes to various start menu shortcut names and model titles

### LINKED ISSUE #718: Start menu model names differ from "model_title"
We recently created `natcap.invest.MODEL_METADATA` as the single source of truth for all the different invest model names. And the `model_title` is the meant to be the user-facing name. It appears in the Mac launcher, in the header of the Qt window (Windows & Mac), and in the Workbench.

One thing we missed is the Windows Start menu shortcut names, which are hardcoded in the NSIS script. At a glance, these models have start menu names different than the `model_title`, so we could update them:

| Start Menu | model_title |
|-------------|--------------|
**Scenic Quality** | Unobstructed Views: Scenic Quality Provision
Water Yield | **Annual Water Yield**
Pollination | **Crop Pollination**
Recreation | **Visitation: Recreation and Tourism**
**Urban Stormwater Retention** Model | Stormwater

I bolded the names that I personally prefer, so I would consider changing those `model_title` as needed also. Would anyone else like to weigh in?

### PR DESCRIPTION
**Pull request by davemfish**
This PR unifies start menu names with model titles, according to what we discussed recently.

Fixes #718

# Checklist
- [x] Updated HISTORY.rst (if these changes are user-facing)

- [x] Updated the user's guide (if needed)  - I renamed the Scenic Quality and Crop Pollination chapters to better match these names. I did that on the `release/3.10` branch of the UG.

### CODE REVIEW

**Comment by davemfish** [comment]
@emlys I'm also happy to update the Stormwater names in this PR if that's settled. Or we can do it separately.

**Comment by emlys** [comment]
@davemfish it looks like the build is failing trying to check out the new UG commit hash... maybe need to push the latest commit? Other than that, this looks good. Let's keep the stormwater name for a separate PR.

**Comment by davemfish** [comment]
> @davemfish it looks like the build is failing trying to check out the new UG commit hash... maybe need to push the latest commit? Other than that, this looks good. Let's keep the stormwater name for a separate PR.

Yes I forgot to push the UG. Everything is passing now @emlys

**Review by emlys — APPROVED** [review]
thanks @davemfish!

**Pull request merged**
