### PR TITLE
Pr resolution #193

### PR DESCRIPTION
**Pull request by richpsharp**
This resolves merge conflicts for PR #193

### CODE REVIEW

**Comment by richpsharp** [comment]
Hey @dcdenu4, this is the first time I've done one of these merge conflict resolution PRs of master into release. I figure you review it since you were the original reviewer of the PR? Let me know if that doesn't sound right.

**Comment by dcdenu4** [comment]
Hey @richpsharp ,

Yea this is definitely a pain point because the conflict is completely lost so it's hard to properly provide any kind of review. However, it looks like some crop tests are failing and I have a very strong suspicion that this is because of GDAL 3 vs GDAL 2. See my PR on bitbucket here for fixing some crop tests: https://bitbucket.org/natcap/invest-test-data/pull-requests/11/updating-expected-test-results-for-using/diff

I'm happy to chat about why I think these results are different and why I thought it was fine to change them to support the GDAL 3 results. Sorry, this is super annoying.

**Comment by richpsharp** [comment]
> Hey @richpsharp ,
> 
> Yea this is definitely a pain point because the conflict is completely lost so it's hard to properly provide any kind of review. However, it looks like some crop tests are failing and I have a very strong suspicion that this is because of GDAL 3 vs GDAL 2. See my PR on bitbucket here for fixing some crop tests: https://bitbucket.org/natcap/invest-test-data/pull-requests/11/updating-expected-test-results-for-using/diff
> 
> I'm happy to chat about why I think these results are different and why I thought it was fine to change them to support the GDAL 3 results. Sorry, this is super annoying.
> 
> If you pull your `pr-resolution` branch back down and run tests in a GDAL 3 environment, you should see the failures.

Ugh so I should have just done the PR from the release branch to begin with.

**Comment by richpsharp** [comment]
Okay I tried to fork off of your crop data but I was getting strange errors there. I think it's best to just reject this PR, then I can address it again from scratch in the release branch.

**Pull request closed without merging**
