### PR TITLE
Include specific dylibs in the pyinstaller build to avoid conflicts on mac

### LINKED ISSUE #10: Homebrew-installed libraries interfere with InVEST mac binaries
When testing out the InVEST 3.8.0 release binaries, I could launch and run the models by reaching into the application and running the compiled `invest` binary.  But then if I tried running a model that loaded geometries from a vector, the model would segfault.  The segfault exception when `n_workers=-1` looked like this:

```
Current thread 0x0000700010e0e000 (most recent call first):
  File "env/lib/python3.7/site-packages/shapely/geometry/polygon.py", line 494 in geos_polygon_from_py
  File "env/lib/python3.7/site-packages/shapely/geometry/polygon.py", line 240 in __init__
  File "env/lib/python3.7/site-packages/shapely/geometry/geo.py", line 19 in box
  File "env/lib/python3.7/site-packages/taskgraph/Task.py", line 1071 in _call
  File "env/lib/python3.7/site-packages/taskgraph/Task.py", line 389 in _task_executor
  File "env/lib/python3.7/threading.py", line 870 in run
  File "env/lib/python3.7/threading.py", line 926 in _bootstrap_inner
  File "env/lib/python3.7/threading.py", line 890 in _bootstrap

Thread 0x0000700010408000 (most recent call first):
  File "env/lib/python3.7/threading.py", line 296 in wait
  File "env/lib/python3.7/threading.py", line 552 in wait
  File "env/lib/python3.7/site-packages/taskgraph/Task.py", line 1231 in join
  File "env/lib/python3.7/site-packages/taskgraph/Task.py", line 713 in join
  File "env/lib/python3.7/site-packages/natcap/invest/scenic_quality/scenic_quality.py", line 458 in execute
  File "env/lib/python3.7/site-packages/natcap/invest/ui/model.py", line 1645 in _logged_target
  File "env/lib/python3.7/site-packages/natcap/invest/ui/execution.py", line 68 in run
  File "env/lib/python3.7/threading.py", line 926 in _bootstrap_inner
  File "env/lib/python3.7/threading.py", line 890 in _bootstrap

Thread 0x000000010b383dc0 (most recent call first):
  File "src/natcap/invest/cli.py", line 561 in main
  File "src/natcap/invest/cli.py", line 575 in <module>
Segmentation fault: 11
```

After digging into this some more, it turned out that my homebrew install had GEOS 3.7.3 and GDAL 3.0.1 installed due to a homebrew-managed QGIS install, and that the InVEST binaries were clearly loading the GEOS binaries from the homebrew `Cellar` (verified by sampling the files that the `invest` process had open, visible in Activity Monitor).  See the [attached sample log](https://github.com/natcap/invest/files/4188072/Sample.of.invest.txt) for more information.

My questions around this are:

1. why was GEOS being loaded from the `Cellar` and not from the bundled binaries?
2. how can we prevent this from happening in the future?

It would appear that [pyinstaller modifies `LD_LIBRARY_PATH` ](https://pyinstaller.readthedocs.io/en/stable/runtime-information.html#ld-library-path-libpath-considerations)... maybe that has something to do with this?

### LINKED ISSUE #82: Mac build issue spotted in 3.8.0 Rec model
These two logs were sent to me. I don't know what's going on here, but maybe it's an issue with a library shipped with the Mac distribution?

The Problem Report includes:
 `Assertion failed: (0), function query, file AbstractSTRtree.cpp, line 293.`

[ProblemReport_14_44_46.txt](https://github.com/natcap/invest/files/4494296/ProblemReport_14_44_46.txt)
[InVEST-Recreation-Model-log-2020-04-08--14_44_46.txt](https://github.com/natcap/invest/files/4494298/InVEST-Recreation-Model-log-2020-04-08--14_44_46.txt)

### PR DESCRIPTION
**Pull request by phargogh**
This PR includes some extra libraries in the pyinstaller build on mac that cause problems on a homebrew-enabled mac under certain circumstances.

Closes #10
Closes #82

### CODE REVIEW

**Review by dcdenu4 — COMMENTED** [review]
@phargogh changes look good to me. I do see that the mac binary builds are failing on a homebrew issue... Since this is a mac specific PR, I think we should wait for this test to pass. Hopefully the homebrew or actions team can get it fixed.

**Comment by phargogh** [comment]
@dcdenu4 I just implemented a workaround for the mac binary issue as suggested by the actions team in https://github.com/actions/virtual-environments/issues/1811#issuecomment-708480190.  Looks like the mac builds are passing again!

**Review by dcdenu4 — APPROVED** [review]
Great. Sorry for the delay here.

**Comment by phargogh** [comment]
No worries at all @dcdenu4 !  I'm really glad you mentioned the mac issue ... I assumed the actions folks were going to resolve something and our mac builds would magically work once again.  It turned out to not be the case and I wouldn't have looked into it otherwise.

**Pull request merged**
