### PR TITLE
Merge latest main into feature/urban-nature-access

### PR DESCRIPTION
**Pull request by phargogh**
This just updates `feature/urban-nature-access` with the latest changes in `main` to help make the review of #944 easier.

### CODE REVIEW

**Review by emlys — APPROVED** [review]
Looks good to me

**Comment by phargogh** [comment]
We can for sure give @dcdenu4 a chance to look this over if he likes! I also just pushed a change that addresses the functional issues with the tests, so hopefully we're good there.

**Review by dcdenu4 — APPROVED** [review]
@phargogh I'm fine merging this. But you mentioned pushing changes to help with the tests failing. They still appear to be failing. I want to make sure what you pushed for that is good to go before merging.

**Comment by phargogh** [comment]
@dcdenu4 thanks for catching that!  I keep forgetting to run the tests for ARGS_SPECs.  I just pushed _another_ change that corrects the failing test (which was failing because of an issue with the UNA ARGS_SPEC).

**Comment by dcdenu4** [comment]
Sorry @phargogh to keep delaying this. Looks like some Workbench tests are failing...

```
  ● validate the UI spec › each model has a complete entry
    expect(received).toContain(expected) // indexOf
    Expected value: "urban_nature_access"
    Received array: ["annual_water_yield", "carbon", "coastal_blue_carbon", "coastal_blue_carbon_preprocessor", "coastal_vulnerability", "crop_production_percentile", "crop_production_regression", "delineateit", "forest_carbon_edge_effect", "globio", "habitat_quality", "habitat_risk_assessment", "ndr", "pollination", "recreation", "routedem", "scenario_generator_proximity", "scenic_quality", "sdr", "seasonal_water_yield", "stormwater", "urban_cooling_model", "urban_flood_risk_mitigation", "wave_energy", "wind_energy"]
```

**Comment by phargogh** [comment]
@dcdenu4 thanks for catching the build failure in the workbench!  I've fixed that issue.  The workbench tests are now failing because there's no UG chapter for UNA and there's no tag for UNA on the forums.

I've bumped the UG repo rev in `Makefile` to point to a new commit in the UG repo that contains a stub of the UNA UG chapter, and I tried creating an initial post about UNA on the forums but I guess it isn't showing up yet?  In any case, I think these failures are OK for now.

**Pull request merged**
