### PR TITLE
Force use of stated nodata value and `float32` dtype in pollination

### LINKED ISSUE #1635: Pollination `farm_pollinators.tif` has `inf` values when run with the sample data
Sibylles on the forums (https://community.naturalcapitalproject.org/t/pollination-python-without-pip-install-gdal-3-3-0/5479/4) identified an issue with the InVEST Pollination model where `farm_pollinators.tif` has `inf` values as nodata, and functionally infinity values in places where there should be reasonable numerical values.

I am observing this on `natcap/invest`, version `3.14.2.post60+gaf8ce8be3`, having just used `make fetch` to get the latest sample data.

To reproduce:
* Run the InVEST pollination model using the sample data
* Open `farm_pollinators.tif` using QGIS to observe values.

### PR DESCRIPTION
**Pull request by phargogh**
This PR updates all calls to `pygeoprocessing.raster_map` to use the pollination-defined nodata constant value, and also updates the dtype to force the output dtype to float32, resulting in smaller filesizes.

Some parts of the model expected a specific nodata value, which meant that `raster_map`'s calculation of a reasonable nodata value was resulting in near-inf outputs in some rasters.

Likely because of the use of convolutions in the pollination model (which create float64 rasters), most of the model outputs were also being created as float64 rasters, which probably isn't strictly necessary.  This change just reverts back to float32 precision, which saves some disk space in the output workspace.

Fixes #1635 

## Checklist
- [x] Updated HISTORY.rst and link to any relevant issue (if these changes are user-facing)
~~- [ ] Updated the user's guide (if needed)~~
~~- [ ] Tested the Workbench UI (if relevant)~~

### CODE REVIEW

**Review by emlys — COMMENTED** [review]
@phargogh the pollination changes make sense to me! In the parts of the model that expect that specific nodata value, I wonder if it might also make sense to instead read the nodata value from the raster properties? Rather than relying on the previously-set value.

There's also some changes in here in `convert-requirements-to-conda-yml.py` and `urban_nature_access.py` that may be unrelated?

**Comment by phargogh** [comment]
OK!  I just pulled in the latest changes from `main` and removed the changes to the conda conversion script that I had made trying to debug build failures.  The UNA change appears to have happened because I must have based this branch off of the branch for https://github.com/natcap/invest/pull/1631, so once it's all looking good, let's merge this after that other PR.

**Comment by emlys** [comment]
Thanks @phargogh! I'm still seeing a deleted comment in UNA, that was not part of #1631 , should that be removed?

**Comment by phargogh** [comment]
@emlys yeah, that was my fault, I think I removed that line in a slightly botched merge conflict resolution!  It should be all addressed now, pending your review and the builds passing.

**Review by emlys — APPROVED** [review]
👍

**Pull request merged**
