### PR TITLE
Don't use "millions of" currency units in Wind Energy

### LINKED ISSUE #741: Don't use "millions of" currency units in Wind Energy
In Wind Energy, some inputs are measured in "millions of currency units" while others are in single currency units. The model depends on this and does some conversions using a factor of 1000000. We should standardize to use currency units everywhere, and not measure in "millions of" anything. Using "millions of" for some inputs creates room for confusion, and it's not universal - we've moved away from requiring US$, but not all currencies are sensibly measured in units of millions.

### PR DESCRIPTION
**Pull request by emlys**
# Description
Fixes #741. 
In my opinion the user's guide makes clear enough already that the default data is in millions of US dollars. I'm also editing the wind energy user's guide page with info that I learned from making these changes, but that can happen separately. 

# Checklist
- [x] Updated HISTORY.rst (if these changes are user-facing)
- [x] Updated the user's guide (if needed)

### CODE REVIEW

**Review by davemfish — COMMENTED** [review]
Hi @emlys this looks good to me. Can you just describe what was changed in the test data? Was it just renaming a raster and re-scaling it by 1000000?

And does the sample data need updating as well to change all those parameter values?

**Comment by davemfish** [comment]
> In my opinion the user's guide makes clear enough already that the default data is in millions of US dollars. 

But shouldn't it be changed along with this PR to not use millions? Also there's the change in one output filename that should be updated in the UG. 

> I'm also editing the wind energy user's guide page with info that I learned from making these changes, but that can happen separately.

**Comment by emlys** [comment]
@davemfish oh you're right, I did need to update that file name. I don't think any of the data in the UG needs to be updated, because the tables that have data in millions of $ are not model inputs. They're just illustrating some real-world examples.

**Comment by emlys** [comment]
Also updated the affected parameters in the sample data. 
>  Can you just describe what was changed in the test data? Was it just renaming a raster and re-scaling it by 1000000?

Basically yeah, multiplying it by 1000000 did not work exactly since there was some change in the floating point error that added up. I spot-checked a couple of numbers and they were mostly close enough to the original expected values * 1000000 (relative difference 1e-6 or so). One was different on the order of 1e-4 to 1e-5, not sure why - the original expected data may have been off slightly too. With `float32` I'd expect that the error might be different, but not greater/less, between integers in the millions and those same numbers divided by 1000000 (xxxxxxx.0 vs x.xxxxxx)?

**Comment by davemfish** [comment]
Hi @emlys , that all sounds good about the UG and the test data. ✔️ 

It looks like the sample data json files are failing to validate. And for some reason this model has a whole bunch of them.

**Comment by emlys** [comment]
Ah, I shouldn't have updated the `invest.users-guide` `release/3.10` branch directly for #568.

**Comment by emlys** [comment]
@davemfish this is ready - the mac build is failing with that unrelated issue

**Review by davemfish — APPROVED** [review]
Thank you!

**Pull request merged**
