### PR TITLE
Always run pollination total abundance step

### LINKED ISSUE #546: Pollination doesn't calculate total abundance without farm vector
Reported [here](https://community.naturalcapitalproject.org/t/missing-total-pollinator-abundance-and-total-pollinator-yield-in-final-results-example-biophysical-table-data/1873) and in emails that followed.

If the optional farm vector is not provided, `execute` finishes without calculating the `total_pollinator_abundance` output, even though it doesn't depend on any farm data. I can't see any reason not to move this step before the `task_graph.close()`, it's just a sum of the individual pollinator abundance outputs, which are created.
The user's guide is not clear about this or that the `total_pollinator_yield` output also depends on the farm vector.

### PR DESCRIPTION
**Pull request by emlys**
# Description
Fixes #546 
Doing this now so I can send a dev build to the user.
Made a `release/3.9.1` branch of the user's guide, with comments clarifying the pollination outputs: https://github.com/natcap/invest.users-guide/tree/release/3.9.1

# Checklist
- [x] Updated HISTORY.rst (if these changes are user-facing)

- [x] Updated the user's guide (if needed)

### CODE REVIEW

**Comment by emlys** [comment]
any idea what's going on here? https://github.com/natcap/invest/blob/32b81de1c748011fc25cc822ff9217ae65aff526/src/natcap/invest/pollination.py#L1406-L1409 🤯 😲

**Comment by phargogh** [comment]
> any idea what's going on here? 

@emlys Pollination was a very early (maybe the first) InVEST model to use `taskgraph`, and this is a super old approach to determining whether the source code had changed.  The code you highlighed reads the source code of the `__call__` method, encodes it as UTF-8 and takes the SHA1 digest.  These days, `taskgraph` handles this all for us behind the scenes, but it does pretty much the same thing.

**Comment by emlys** [comment]
> This digest is then used to determine if the task needs to be recomputed if/when the source code changes. These days, taskgraph handles this for us behind the scenes, but it does pretty much the same thing.

Wacky! So if the same function name is called with the same arguments, but the source code is different, it would know to re-run the task? Very cool

**Review by dcdenu4 — APPROVED** [review]
Hey @emlys , this looks good to me. Thanks for the Users Guide note. 

I was wondering if there should be an added test, but in this case it would just be testing that outputs are generated regardless of farm vector... which doesn't seem that helpful.

**Pull request merged**
