### PR TITLE
Unpin gdal and update sdr test expected values

### LINKED ISSUE #905: SDR tests are failing with gdal=3.4.2
Three SDR tests are failing on github actions:
```
test_base_regression: AssertionError: these key (actual/expected) errors occured: {'usle_tot': (13.90210914612, 14.25030517578), 'sed_export': (0.55185163021, 0.60502111912), 'sed_dep': (8.80612564087, 9.05251502991)}

test_drainage_regression: AssertionError: these key (actual/expected) errors occured: {'sed_export': (0.97192692757, 1.02959537506), 'usle_tot': (12.68887424469, 12.97211265564)}

test_regression_with_undefined_nodata: AssertionError: these key (actual/expected) errors occured: {'sed_export': (0.55185163021, 0.60502111912), 'usle_tot': (13.90210914612, 14.25030517578)}
```
These passed when I ran them locally. Possibly an updated dependency?

### PR DESCRIPTION
**Pull request by emlys**
## Description
Fixes #905 

## Checklist
- [x] Updated HISTORY.rst (if these changes are user-facing)
- [ ] ~Updated the user's guide (if needed)~
- [ ] ~Tested the affected models' UIs (if relevant)~

### CODE REVIEW

**Comment by emlys** [comment]
Not sure if this needs a history note, since it could affect model results, but that's due to a change in GDAL not invest.

**Review by dcdenu4 — CHANGES_REQUESTED** [review]
Thanks for circling back to this @emlys. Am I right in thinking that these tests would now fail if using an older version of gdal < 3.4.2? If that's the case would we want to set our gdal dependency to gdal>3.4.2?

I think a note in history could be appropriate since it's not an insignificant change in SDR values. Maybe something like:
- Updating SDR test values due to a GDAL improvement in its `mode` resampling algorithm. [see this issue]

What do you think?

**Comment by emlys** [comment]
@dcdenu4 I added a history note. I don't think we need to require `gdal>=3.4.2` because invest runs just fine with earlier versions. The results are just different. If a user wanted the results from an older version of gdal, I think that should be allowed.

**Comment by dcdenu4** [comment]
>invest runs just fine with earlier versions. The results are just different. If a user wanted the results from an older version of gdal, I think that should be allowed.

Definitely.

I guess I'm just hung up with what would happen if I was working from `invest/main` but had `gdal=3.3.0` and I ran SDR tests? With the updated values, those tests would fail right? Sorry if I'm completely thinking about this wrong...

**Comment by emlys** [comment]
> With the updated values, those tests would fail right?

You're right they would, I guess it's a question of whether `requirements.txt` should be strict enough that the tests pass? Or just enough that someone can run invest without errors?

**Comment by dcdenu4** [comment]
Hey @phargogh and @davemfish , this was the other issue we touched on in our last Friday call. As a reminder, this PR updates some SDR tests to pass given `gdal>=3.4.2` which made improvements to its resampling algorithms. The question is, should we also pin gdal as a requirement to `gdal>=3.4.2` in the process?

**Comment by davemfish** [comment]
> Hey @phargogh and @davemfish , this was the other issue we touched on in our last Friday call. As a reminder, this PR updates some SDR tests to pass given `gdal>=3.4.2` which made improvements to its resampling algorithms. The question is, should we also pin gdal as a requirement to `gdal>=3.4.2` in the process?

I think it would make our lives slightly easier to require `gdal>=3.4.2`. Just to avoid the case Doug brought up of building an environment where tests don't pass.

> I don't think we need to require gdal>=3.4.2 because invest runs just fine with earlier versions. The results are just different. If a user wanted the results from an older version of gdal, I think that should be allowed.

I agree user's should be able to reproduce their results, but I think it's reasonable to say they should install an older version of invest to do so, not just an older version of gdal.

**Comment by emlys** [comment]
@dcdenu4 I added the requirement `gdal>=3.4.2`. It's causing a ReadTheDocs build error but I'm not sure if there's anything we can do about that. I'll leave it up to whether to merge or wait and see if the RTD issue resolves - possibly #1037 will help?

**Review by dcdenu4 — APPROVED** [review]
Thanks @emlys ! I think it's okay to go ahead with this with the RTD failing.

**Pull request merged**
