### PR TITLE
Fixing GHA MacOS-workbench failures

### LINKED ISSUE #1186: Puppeteer tests are flaky
Lately it seems like the "Build binaries" workflow is most likely to randomly fail, and it usually fails on the puppeteer step. For example, on the latest commit on main, the checks [originally passed](https://github.com/natcap/invest/actions/runs/4127028065/attempts/1), but the mac binary build [failed on a rerun](https://github.com/natcap/invest/actions/runs/4127028065/attempts/2), with these errors:

> `objc[58407]: Class WebSwapCGLLayer is implemented in both /System/Library/Frameworks/WebKit.framework/Versions/A/Frameworks/WebCore.framework/Versions/A/Frameworks/libANGLE-shared.dylib (0x7ffb54cadec8) and /Users/runner/work/invest/invest/workbench/dist/mac/InVEST 3.12.1.post21+gba5d36231 Workbench.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libGLESv2.dylib (0x10b7e89c8). One of the two will be used. Which one is undefined.`

> `'Failed to fetch browser webSocket URL from http://localhost:9009/json/version: request to http://localhost:9009/json/version failed, reason: connect ECONNREFUSED ::1:9009'`

> `TypeError: Cannot read properties of undefined (reading 'close')
        at _callee2$ (/Users/runner/work/invest/invest/workbench/tests/binary_tests/puppet.test.js:133:19)
    expect(received).toBeTruthy()
        at tryCatch (/Users/runner/work/invest/invest/workbench/node_modules/regenerator-runtime/runtime.js:63:40)
    ...`

### LINKED ISSUE #1207: GHA failures on MacOS-Workbench steps
Two failures are increasingly common, almost to the point where they never pass:

https://github.com/natcap/invest/actions/runs/4287788944/jobs/7485789357
1. Mac Workbench Tests
2. Mac Binary Builds

The Workbench tests fail on `flaskapp.test.js` which starts a flask server as a subprocess before running the tests. The test never receives the signal that the server is ready before timing out in the `beforeAll` setup.

The builds fail during the puppeteer test, noted also in #1186 . That test setup also involves starting subprocesses (electron, which in turns starts a python/flask subprocess).

The same tests appear reliable on Windows.

### PR DESCRIPTION
**Pull request by davemfish**
Various fixes to problematic steps in our builds, mainly on MacOS-Workbench steps. Steps that involved NodeJS launching a subprocess were especially problematic on Mac. Maybe for some of the reasons discussed here: https://github.com/desktop/desktop/issues/13639

Without fully getting to the bottom of it, upgrading Node seemed to work. As well as resolving some race conditions in our tests. 

The Node upgrade required changing all the `localhost` to `127.0.0.1` as some IP address resolution stuff seemed to change. 

Fixes #1207 
Fixes #1186 

## Checklist
- [ ] Updated HISTORY.rst and link to any relevant issue (if these changes are user-facing)
- [ ] Updated the user's guide (if needed)
- [ ] Tested the affected models' UIs (if relevant)

### CODE REVIEW

**Review by emlys — CHANGES_REQUESTED** [review]
thanks for doing this @davemfish! I don't completely understand the root cause either, but the changes here make sense. It does look like the changes in `main.test.js` are failing on windows now, though.

**Comment by davemfish** [comment]
> thanks for doing this @davemfish! I don't completely understand the root cause either, but the changes here make sense. It does look like the changes in `main.test.js` are failing on windows now, though.

Yes, that last test failure is the bane of my existence right now. Seems it's another race condition that popped up after upgrading Node. I'll keep trying...

**Comment by davemfish** [comment]
Okay @emlys I updated that last failing Windows test again. Hopefully that does it.

**Review by emlys — APPROVED** [review]
👍

**Pull request merged**
