### PR TITLE
Update the layer name of delineated watersheds

### LINKED ISSUE #310: Update DelineateIt to include suffix in watersheds vector layer
Once https://github.com/natcap/pygeoprocessing/issues/119 is finished and released, we'll want to update DelineateIt to define the layer name to include the suffix.  `f"watersheds{suffix}"` would be the functional equivalent of what is currently released in InVEST, just with the suffix added in.

Related to #56

### PR DESCRIPTION
**Pull request by phargogh**
This PR fixes #310 by adding the suffix to the layer name of the delineated watershed vector.

### CODE REVIEW

**Review by dcdenu4 — APPROVED** [review]
Looks pretty straight forward to me!

**Comment by dcdenu4** [comment]
Hey @phargogh I approved this PR but see that tests have cancelled out, probably due to the rec tests. Would you like to wait until these tests have a chance to re-run and pass?

**Comment by dcdenu4** [comment]
> Hey @phargogh I approved this PR but see that tests have cancelled out, probably due to the rec tests. Would you like to wait until these tests have a chance to re-run and pass?

Just kidding, it looks like a mac test is failing because it is grabbing GDAL 3.1.3?

**Comment by phargogh** [comment]
Yep, failing because https://github.com/conda-forge/gdal-feedstock/pull/410 is just sitting there waiting for a bugfix.  I've pushed a revision to cap the GDAL version to accommodate this issue with conda-forge.

**Comment by phargogh** [comment]
OK!  Everything looks like it's passing now except for some unexpected error when uploading the mac binaries to a release object (which, come to think of it, shouldn't be happening anyways).

**Comment by phargogh** [comment]
@dcdenu4 I confirmed that the part of the workflow that was mysteriously failing was indeed no longer needed as part of our bugfix release checklist, so rev b772a5b removes this unneeded part of the workflow.  Just waiting now for tests to pass and then I think maybe this'll be complete unless anything else comes to mind!

**Comment by dcdenu4** [comment]
Great! Everything looks good. Thanks James.

**Pull request merged**
