### PR TITLE
Merge `main` into `release/3.12`

### PR DESCRIPTION
**Pull request by phargogh**
This PR merges `main` into `release/3.12`.

### CODE REVIEW

**Review by dcdenu4 — APPROVED** [review]
Weird that these missed the boat in an auto merge! Looks good to me.

**Comment by emlys** [comment]
It seems suspicious that there are no changes to `tests/test_sdr.py` in this diff, and it also hasn't been updated on `release/3.12` already

**Comment by phargogh** [comment]
@emlys I think these have inadvertently already been updated on `release/3.12`!  When I look at the [changes you made to the SDR tests](https://github.com/natcap/invest/pull/1053/commits/c38a161c6505c393066a23003dbe542e55833c89) compared with [what's already on `release/3.12`](https://github.com/natcap/invest/blob/release/3.12/tests/test_sdr.py#L288) show that they match.  Are you seeing that as well?

If you are, this would be a relief to me because that means that I inadvertently broke the `release/3.12` tests in the SDR PEP PR https://github.com/natcap/invest/pull/1016 and the problem was that I was running the wrong local version of GDAL.

**Comment by dcdenu4** [comment]
These changes are now taking place in #1057, and we talked through the confusion with SDR test values on a call.

**Pull request closed without merging**
